# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariage', '0010_auto_20160221_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
